"""Pydantic models for AI-powered resume enrichment."""

from typing import Annotated, Literal

from pydantic import BaseModel, Field, model_validator

from app.ai_limits import validate_source_size
from app.schemas.diff import DiffRow

# "entry" targets one entry's bullets; "values" targets a flat list of short
# values (a TAGS section, or one group of a GROUPS section). Which section
# holds them is the user's choice, so the type says what the content *is*,
# never which section it came from.
EnrichmentItemType = Literal["entry", "values"]
RegenerateItemType = EnrichmentItemType


class EnrichmentItem(BaseModel):
    """An item identified by AI as needing enrichment."""

    item_id: str  # "<section_key>:<entry_id>" or "<section_key>:#tags"
    item_type: EnrichmentItemType
    # The owning section's heading, for display. The UI labels an item with
    # the user's own section name; "Experience"/"Projects" are no longer
    # categories the code knows about.
    section_heading: str = ""
    title: str  # Entry title
    subtitle: str | None = None  # Entry subtitle (company, institution, role)
    current_description: list[str] = Field(default_factory=list)
    weakness_reason: str  # Why AI flagged this item


class EnrichmentQuestion(BaseModel):
    """A clarifying question generated by AI for an item."""

    question_id: str  # Unique question ID (e.g., "q_0")
    item_id: str  # Which item this question relates to
    question: str  # The question text
    placeholder: str = ""  # Hint for the input field


class AnalysisResponse(BaseModel):
    """Response from AI resume analysis."""

    items_to_enrich: list[EnrichmentItem] = Field(default_factory=list)
    questions: list[EnrichmentQuestion] = Field(default_factory=list)
    analysis_summary: str | None = None  # Optional overall summary


class AnswerInput(BaseModel):
    """User's answer to a clarifying question."""

    question_id: str
    answer: str = Field(max_length=6000)
    item_id: str | None = None  # When provided, skips redundant re-analysis
    question_text: str | None = Field(
        default=None, max_length=2000
    )  # Original question for prompt context in fast path


class EnhanceRequest(BaseModel):
    """Request to generate enhanced descriptions from answers."""

    resume_id: str
    answers: list[AnswerInput] = Field(max_length=40)

    @model_validator(mode="after")
    def _validate_source_budget(self) -> "EnhanceRequest":
        validate_source_size(self.model_dump(mode="json"))
        return self


class EnhancedDescription(BaseModel):
    """AI-generated enhanced description for an item."""

    item_id: str
    item_type: EnrichmentItemType
    section_heading: str = ""
    title: str  # For display purposes
    original_description: list[str] = Field(default_factory=list)
    enhanced_description: list[str] = Field(default_factory=list)


class EnhancementItemError(BaseModel):
    """A safe, non-fatal error for one requested enhancement item."""

    item_id: str
    item_type: EnrichmentItemType
    section_heading: str = ""
    title: str
    subtitle: str | None = None
    message: str


class EnhancementPreview(BaseModel):
    """Preview of all enhancements before applying."""

    enhancements: list[EnhancedDescription] = Field(default_factory=list)
    errors: list[EnhancementItemError] = Field(default_factory=list)


class ApplyEnhancementsRequest(BaseModel):
    """Request to apply enhancements to the master resume."""

    enhancements: list[EnhancedDescription]


# ============================================
# AI Regenerate Feature Schemas
# ============================================

class RegenerateItemInput(BaseModel):
    """Input for a single item to regenerate."""

    # "<section_key>:<entry_id>" for an entry; "<section_key>:#tags" or
    # "<section_key>:#group:<index>" for a value list. Entry ids are stable
    # for the entry's life, so a reorder between preview and apply cannot
    # silently retarget a different entry.
    item_id: str
    item_type: RegenerateItemType
    title: str
    subtitle: str | None = None
    current_content: list[Annotated[str, Field(max_length=6000)]] = Field(
        default_factory=list, max_length=100
    )


class RegenerateRequest(BaseModel):
    """Request to regenerate selected resume items."""

    resume_id: str
    items: list[RegenerateItemInput] = Field(max_length=20)
    instruction: str = Field(max_length=2000)  # User's feedback/instruction for improvement
    output_language: str = "en"

    @model_validator(mode="after")
    def _validate_source_budget(self) -> "RegenerateRequest":
        validate_source_size(self.model_dump(mode="json"))
        return self


class RegeneratedItem(BaseModel):
    """Regenerated content for one item."""

    item_id: str
    item_type: RegenerateItemType
    title: str
    subtitle: str | None = None
    original_content: list[str] = Field(default_factory=list)
    new_content: list[str] = Field(default_factory=list)
    # Server-computed comparison of original_content against new_content,
    # with word-level spans — the same rows the document diff produces, so
    # one UI renders both surfaces.
    rows: list[DiffRow] = Field(default_factory=list)
    diff_summary: str = ""  # AI-generated summary of changes


class RegenerateItemError(BaseModel):
    """A non-fatal error for a single item regeneration request."""

    item_id: str
    item_type: RegenerateItemType
    title: str
    subtitle: str | None = None
    message: str


class RegenerateResponse(BaseModel):
    """Response with all regenerated items."""

    regenerated_items: list[RegeneratedItem] = Field(default_factory=list)
    errors: list[RegenerateItemError] = Field(default_factory=list)
